spring:
  datasource:
    ccms:
      url: jdbc:mysql://127.0.0.1:3306/tecachecache_loyalty2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456

      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      maxIdle: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    benefit:
      url: jdbc:mysql://127.0.0.1:3306/tecachecache_loyalty2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456

      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      maxIdle: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


scheduled:
  pointJob: 0 */10 * * * ?
  pointMember: 0 */10 * * * ?
  pushMember: 0 */5 * * * ?
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

sign:
  app_key: 6000004
  app_secret: ca5733dd233f62ca3b2d559c67442faf
  memberAppsecret: n#gu2a&a5togt1zqa^fs$$8lrgl^u*nc
logging:
  level:
    com.example.springbootpro.mapper: DEBUG
    com.example.springbootpro.benefitMapper: DEBUG
loyalty:
  buildCardUrl: http://ual.pecachecahe.saasproj.shuyun.com/loyalty2-mg/1.0/if/members
  memberAndGradeUrl: http://ual.pecchecache.saasproj.shuyun.com/loyalty2-mg/1.0
  secret: asdfghjksl12
  etoUrl: https://ecrm-cachcache.woaap.com/api/send-template-message
ur:
  sendCoupon: https://api.cche-cache.cn/restur/createCoupon
  postCustomer: https://apicache-cache.cn/restur/postCustomer
  keyId: 75d36629-6cbc-42e4-7ee-5920910b7a30
benefit:
  createCoupon: http://beneft.pecachecache.saasproj.shuyun.com/benefit/1.0/benefit/platform/userBcode/send