spring:
  datasource:
    ccms:
      url: jdbc:mysql://127.0.0.1:3306/tecachecache_loyalty2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      maxIdle: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    benefit:
      url: jdbc:mysql://127.0.0.1:3306/tecachecache_loyalty2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      url: jdbc:mysql://rm-bp13z2fw53w4w8kfm.mysql.rds.aliyuncs.com:3306/benefit?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20



#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

sign:
  app_key: 1000001
  app_secret: 32bbd3f271f236754d424d443e80fbe4
  memberAppsecret: n#gu1a&a5togt1zqa^fs$$8lrgl^u*nc
scheduled:
  timing: 0 */1 * * * ?
logging:
  level:
    com.example.springbootpro.mapper: DEBUG
    com.example.springbootpro.benefitMapper: DEBUG